version: '3.8'
services:
  app:
    build:
      context: .
    ports:
      - '3000:3000'
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - my-network

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
